// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkgXFV-5InzF1fDLSzwgXAVrBgTuneMEM',
    appId: '1:359890150128:web:3ed32e31d76133d34ad835',
    messagingSenderId: '359890150128',
    projectId: 'user-auth-cda3c',
    authDomain: 'user-auth-cda3c.firebaseapp.com',
    storageBucket: 'user-auth-cda3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHeKJPTOThz_S4stBudzLMDw7Tv74Y42g',
    appId: '1:359890150128:android:06ffb20b6333d77c4ad835',
    messagingSenderId: '359890150128',
    projectId: 'user-auth-cda3c',
    storageBucket: 'user-auth-cda3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa0nSQzCzzEicF7C2GCPhsD72EPFOJayk',
    appId: '1:359890150128:ios:a9f2e1e85d549eb94ad835',
    messagingSenderId: '359890150128',
    projectId: 'user-auth-cda3c',
    storageBucket: 'user-auth-cda3c.appspot.com',
    iosBundleId: 'com.example.authUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa0nSQzCzzEicF7C2GCPhsD72EPFOJayk',
    appId: '1:359890150128:ios:a9f2e1e85d549eb94ad835',
    messagingSenderId: '359890150128',
    projectId: 'user-auth-cda3c',
    storageBucket: 'user-auth-cda3c.appspot.com',
    iosBundleId: 'com.example.authUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkgXFV-5InzF1fDLSzwgXAVrBgTuneMEM',
    appId: '1:359890150128:web:be1ad900cd4ca03c4ad835',
    messagingSenderId: '359890150128',
    projectId: 'user-auth-cda3c',
    authDomain: 'user-auth-cda3c.firebaseapp.com',
    storageBucket: 'user-auth-cda3c.appspot.com',
  );
}
